### ISSUE TITLE
Failure to compile due to cortex-m v0.4.3

### ISSUE THREAD

**Issue by Inityx** [thejpster/launchpad-rs#7]
Building on `rustc 1.43.0-nightly (2890b37b8 2020-03-06)` fails due to [`untagged-option v0.1.1`](https://github.com/jonas-schievink/untagged-option), a dependency of [`cortex-m v0.4.3`](https://github.com/rust-embedded/cortex-m/releases/tag/v0.4.3):

```
error[E0740]: unions may not contain fields that need dropping
--> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/untagged-option-0.1.1/src/lib.rs:53:5
|
53 |     pub some: T,
|     ^^^^^^^^^^^
|
note: `std::mem::ManuallyDrop` can be used to wrap the type
--> $HOME/.cargo/registry/src/github.com-1ecc6299db9ec823/untagged-option-0.1.1/src/lib.rs:53:5
|
53 |     pub some: T,
|     ^^^^^^^^^^^
```

This dependency was made optional in [v0.6.1 (2018-04-05)](https://github.com/rust-embedded/cortex-m/commit/bff66f8fa796e305df93f28d9a5e352eb51596e5#diff-80398c5faae3c069e4e6aa2ed11b28c0L16), and removed in [v0.6.2 (2018-04-26)](https://github.com/rust-embedded/cortex-m/commit/b098b6af6aa48826aa1471ba3359a42d6d3e059a#diff-80398c5faae3c069e4e6aa2ed11b28c0L26).

The problematic dependency closure:
```
stellaris-launchpad v0.11.2
├── cortex-m v0.4.3
│   └── untagged-option v0.1.1
└── lm4f120 v0.10.0
     ├── cortex-m v0.4.3
     └── tm4c123x v0.6.1
          └── cortex-m v0.4.3

```

**Comment by Inityx** [comment]
Upgrading `cortex-m` to v0.6 appears to break only `common::startup::isr_hardfault_rs`, as its parameter type `ExceptionFrame` has been moved to [`cortex_m_rt`](https://docs.rs/cortex-m-rt/0.6.12/cortex_m_rt/struct.ExceptionFrame.html).

**Comment by thejpster** [comment]
So this crate is largely abandoned in favour of tm4c-hal. Happy to take a PR though.

**Comment by Inityx** [comment]
Thanks for the response! Given that the other crate seems to be more in line with current best practices, I'll use it instead.
